version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    #ports:
    #  - "3306:3306"

  backend:
    image: lillykate16/c0l0rscapes-backend:latest
    container_name: c0l0rscapes-backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: lillykate16/c0l0rscapes-frontend:latest
    container_name: c0l0rscapes-frontend
    ports:
      - "80:80"

volumes:
  db-data:
